### ISSUE TITLE
Where is the spec governing tests 0073 and 0074?

### ISSUE THREAD

**Issue by HansBrende** [w3c/microdata-rdf#29]
I'm overhauling [Any23](https://github.com/apache/any23)'s microdata extractor and so far all of our microdata tests are passing except tests 0073 and 0074.  In both cases the result is expecting a 

`_:0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://expansion/AdditionalType> `

triple to be generated, but it is not. I can't seem to find anything in the conversion algorithm which states that any `itemprop` named "subpropertyOf" or "equivalentProperty" should be treated as if it were a registry entry key with the same name. I don't see any registry specified for those two tests, so I'm assuming we're using the default registry and the only vocabulary expansion that should happen is for `http://schema.org/additionalType`. Am I incorrect?

Wouldn't we need a registry entry such as the following:

```
{
    "http://expansion/": {
        "properties": {
            "subPropertyOf": {"subPropertyOf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"}
        }
    }
}
```

in order to generate the desired triple?

**Comment by gkellogg** [comment]
Note that if the [new Microdata spec](https://www.w3.org/TR/microdata/) is ever published, this note will likely be obsoleted, and the tests may be different.

There is a [test-registry](https://github.com/w3c/microdata-rdf/blob/gh-pages/tests/test-registry.json) defined that the test harness is intended to include when running these tests, which defines expansion rules for `equivalentProperty` and `subPropertyOf`, which defines their relationship to `rdf:type`, so that following the expansion rules, you would infer the `rdf:type` relationship. The [test readme](http://w3c.github.io/microdata-rdf/tests/) describes how to run the tests. Expansion rules are defined in [Vocabulary Expansion](https://www.w3.org/TR/microdata-rdf/#vocabulary-expansion), based on what's in the registry. Also see 9.1.6 in [6.2 Generate the triples](https://www.w3.org/TR/microdata-rdf/#generate-the-triples).

The new spec doesn't have such tools, and results will be subtly different, but it's a simpler road spec to specify. Of course, it hasn't been updated since April, and I'm not sure what its status is in the Web Platform Group. @chaals would know better.

**Comment by HansBrende** [comment]
Ah, apologies, I totally missed the link to the test registry on the web page! Thanks for pointing it out. Might be more obvious if you include a link to the correct registry in *each* manifest entry (I just assumed that any manifest entries which didn't include a registry link defaulted to the standard default registry.)

In that case, Any23 is all up to date! (Although we don't support custom user-supplied registries yet, so I will simply be ignoring tests 73 & 74 for the time being.)

**Comment by HansBrende** [comment]
Oh, and FYI, one issue I found while parsing the turtle test manifest entries is that the type used for negative evals is actually `http://www.w3.org/ns/rdftest#TestMicrodataNegativeSyntax`, but the webpage states that it is `http://www.w3.org/ns/rdftest#TestMicrodataNegativeEval`. This could just be my misunderstanding, but I worked around it by simply using any type prefixed by `http://www.w3.org/ns/rdftest#TestMicrodataNegative` as a negative eval test.

**Comment by gkellogg** [comment]
It should be a negative syntax test, as it should not generate a result to be compared, but generate an error. The manifest should define `TestMicrodataNegativeSyntax`, but doesn't as you noted. Not likely to update at this point.
